[build]
  # Publish the root directory where index.html is located
  publish = "."

  # No build command necessary since these are static files
  # (Netlify might default to 'npm run build' otherwise)
  command = "# no build command"
